on:
  push:
    branches: [main]

name: CD Prod

jobs:
  deploy-frontend-production:
    name: Deploy Frontend Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: npm install & build
        working-directory: ./app
        env:
          CI: false # This is set to false so that warnings don't break the build
        run: |
          npm install
          REACT_APP_ENV=production npm run build

      - name: Deploy app build to S3 bucket
        working-directory: ./app
        run: aws s3 sync ./build/ s3://daniel-quinones-react-app-demo --acl public-read --delete --paths /*
